### ISSUE TITLE
Installation instruction should list ext.js dependency

### ISSUE THREAD

**Issue by proppy** [endtwist/AjaxIM#33]
Hi,

After installation and trying to run the server according to the README instructions, I had the following error:
    aminche:~/AjaxIM# node server/app.js 

```
node.js:275
    throw new Error("Cannot find module '" + request + "'");
      ^
Error: Cannot find module 'ext'
at loadModule (node.js:275:15)
at require (node.js:411:14)
at Object.<anonymous> (/root/AjaxIM/server/app.js:6:22)
at Module._compile (node.js:461:23)
at Module._loadScriptSync (node.js:468:10)
at Module.loadSync (node.js:338:12)
at Object.runMain (node.js:521:24)
at node.js:751:10
```

**Comment by proppy** [comment]
I believe the following commit fix this issue:
http://github.com/proppy/AjaxIM/commit/a16b250bd1e33d6713e908df0be3fddda8f62659

Feel free to pull from:
http://github.com/proppy/AjaxIM/tree/33-extjs-dependency-readme

**Comment by proppy** [comment]
Turned this issue into a pull request with a linked issue:
http://github.com/endtwist/AjaxIM/pull/34
http://github.com/endtwist/AjaxIM/issues#issue/34

Sorry for the noise.
